Revert "gralloc: Fix issue with mmap/munmap meta due to reserved size"
hardware/qcom-caf/sdm660/display/gralloc/gr_buf_mgr.cpp:108:43: error: no member named 'reserved_size' in 'private_handle_t'
  uint64_t reserved_region_size = handle->reserved_size;
                                  ~~~~~~  ^
hardware/qcom-caf/sdm660/display/gralloc/gr_buf_mgr.cpp:127:45: error: no member named 'reserved_size' in 'private_handle_t'
    uint64_t reserved_region_size = handle->reserved_size;
                                    ~~~~~~  ^
hardware/qcom-caf/sdm660/display/gralloc/gr_buf_mgr.cpp:754:41: error: no member named 'reserved_size' in 'private_handle_t'
  auto meta_size = getMetaDataSize(hnd->reserved_size);
                                   ~~~  ^
hardware/qcom-caf/sdm660/display/gralloc/gr_buf_mgr.cpp:1092:8: error: no member named 'reserved_size' in 'private_handle_t'
  hnd->reserved_size = static_cast<unsigned int>(descriptor.GetReservedSize());
  ~~~  ^
4 errors generated.

This reverts commit ff17798121b2762d476ba0a45e7cb96eb602183e.